variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:3.3.9-jdk-8

stages:
  - test
  - deploy

test:
    stage: test
    tags:
      - bash
    script:
      - mvn clean package
 
deploy: 
    stage: deploy
    tags:
      - bash
    script:
      - mvn spring-boot:run
      