spring:
  datasource:
          platform: h2
          url: jdbc:h2:mem:appbanco
          username: sa
          password: sa
          driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true
