spring:
  datasource:
          url: jdbc:h2:file:~/data/demo
          username: sa
          password: sa
          driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
