spring:
  datasource:
          url: jdbc:sqlserver://bancoapp.database.windows.net:1433;database=bancoteste
          username: springapi
          password: apiService01
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
      show-sql: true
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      hibernate.ddl-auto: update
server:
     port: 80